### ISSUE TITLE
Readme Assets

### ISSUE THREAD

**Issue by camenduru** [camenduru/text2video-zero-colab#1]
![examples](https://user-images.githubusercontent.com/54370274/228434661-056f445b-3998-4918-b2fb-3e82ec022080.gif)

**Comment by camenduru** [comment]
![image (6)](https://user-images.githubusercontent.com/54370274/228700984-46ac3613-a53a-46d2-a3f1-122b5550fbee.gif)
![image_5](https://user-images.githubusercontent.com/54370274/228700990-f1c76506-027c-4ede-bdd1-685069724547.gif)

**Comment by G-force78** [comment]
Thanks for the collab! Is there  a way to increase length and frames? It looks like it could be done in the model.py or text2videogenerator.py but not sure if thats the right place?

EDIT: It was the right place, I changed the length in model.py here by changing num_frames

```

    def process_text2video(self, prompt, motion_field_strength_x=12,motion_field_strength_y=12, n_prompt="", resolution=512, seed=24, num_frames=20, fps=2, t0=881, t1=941,
                           use_cf_attn=True, use_motion_field=True, 
                           smooth_bg=False, smooth_bg_strength=0.4 ):
```

**Comment by camenduru** [comment]
huggingface diffusers issues 2898
![Screenshot 2023-04-13 140852](https://user-images.githubusercontent.com/54370274/231741232-73966f17-6d31-4ea8-a239-e7f28354d2e4.png)
